<a href="https://colab.research.google.com/github/dudanobree26/programa-generationAD2-python/blob/main/manipulando_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#para instalar uma blibioteca, eu uso o comendo;
#no colab - !pip install
# fora do colab é apenas pip ilnstall
!pip install pandas
!pip install numpy

In [ ]:
#para conseguir usar a bliblioteca precisamos importar ela
import pandas as pd # <- IMPORT nome_da_bliblioteca AS apelido_para_uso

In [ ]:
#esqueleto do arquivo
#vamos usar dicionarios oara criar os dados
#dicionarios funciona com a aideia de chave->valor ou chave->valores

dados = {
    'nomes':['andre','paulo','aline','paola'],
    'idade':[36,25,30,18],
    'cidade':['Sorocaba','indaiatuba','sao paulo','registro']
}
#a pandas pode tranformar um dicionario em uma "tabela"
#esse pedaço de tabela é chamado de dataframe

#para tranformar
df_dados = pd.DataFrame(dados)

#print(df_dados)

display(df_dados)

   nomes  idade      cidade
0  andre     36    Sorocaba
1  paulo     25  indaiatuba
2  aline     30   sao paulo
3  paola     18    registro

   nomes  idade      cidade
0  andre     36    Sorocaba
1  paulo     25  indaiatuba
2  aline     30   sao paulo
3  paola     18    registro

In [ ]:
#ciar um arquivo csv (excel)

#para criar , precisamos de dados
#chamamos os dados e atibuimos uma funcao -> "to_------" (nome, index)

df_dados.to_csv("teste_dados.csv",index= False)

In [ ]:
#como ler um arquivo que me enviaram

df_ler_dados = pd.read_csv('/content/teste_dados.csv')

#comando para ler as primeiras infos do arquivo
df_ler_dados.head()

   nomes  idade      cidade
0  andre     36    Sorocaba
1  paulo     25  indaiatuba
2  aline     30   sao paulo
3  paola     18    registro

In [ ]:
# vamos popular a tabela

novos_dados = {
    'nome':['Flávia','Cláudio','Fernanda'],
    'idade':[50,63,32],                      #isso é uma blibioteca
    'cidade':['Sorocaba','Iguape','Curitiba']
}
df_novos_dados = pd.DataFrame(novos_dados)
# sempre que eu quero trabalhar com dados, preciso fazer ser dados
# agora temos que juntar o antigo com o novo
# juntar = concatenar
# cria a base que vai receber todos os dados
# usa a função pd.concat para 'juntar' os dados
# pd.concat([dados_antigos, dados_novos], ignore_index=True)
df_dados_juntos = pd.concat([df_ler_dados, df_novos_dados], ignore_index=True)

# voltar para o csv
df_dados_juntos.to_csv('teste_dados.csv', index=False)
display(df_dados_juntos)

   nomes  idade      cidade      nome
0  andre     36    Sorocaba       NaN
1  paulo     25  indaiatuba       NaN
2  aline     30   sao paulo       NaN
3  paola     18    registro       NaN
4    NaN     50    Sorocaba    Flávia
5    NaN     63      Iguape   Cláudio
6    NaN     32    Curitiba  Fernanda